---
- hosts: all
  sudo: yes
  tasks:
    - name: Print Hello World
      debug: msg="hello world"
    - name: install jdk
      yum: 
        name: java-1.8.0-openjdk
    - name: install redis
      get_url: >
        url=http://download.redis.io/releases/redis-3.2.12.tar.gz
        dest=/tmp/redis-3.2.12.tar.gz
    - name: extra redis
      unarchive:
        src=/tmp/redis-3.2.12.tar.gz
        dest=/usr/local
    - name: change owner
      file: >
        state=directory
        path=/usr/local/redis-3.2.12
        owner=vagrant
        group=vagrant
        recurse=yes
    - name: create symlink
      file: >
        state=link
        src=/usr/local/redis-3.2.12
        path=/usr/local/redis
    - name: create path
      lineinfile: >
        state=present
        dest=~/.bashrc
        line="$PATH:/usr/local/redis/bin" 
        create=yes



